## Enable caching of prompts (default: False)
cache-prompts: true

## Suggested number of tokens to use for repo map, use 0 to disable
map-tokens: 2048

## Use colors suitable for a dark terminal background (default: False)
dark-mode: true

## Enable/disable streaming responses (default: True)
stream: false

## Set the markdown code theme (default: default, other options include monokai, solarized-dark, solarized-light, or a Pygments builtin style, see https://pygments.org/styles for available themes)
code-theme: solarized-dark

## Only consider files in the current subtree of the git repository
subtree-only: false

## Enable/disable auto commit of LLM changes (default: True)
auto-commits: false

## Enable/disable watching files for ai coding comments (default: False)
watch-files: true

## Check for new aider versions on launch
check-update: false

## Use VI editing mode in the terminal (default: False)
vim: true
